esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

esphome:
  name: ${device_name}
  includes:
    - <bitset>

logger:
  level: INFO
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG

ota:
  platform: esphome
  password: !secret ota_password

debug:
  update_interval: 5s

preferences:
  flash_write_interval: 1min

time:
  - platform: sntp
    id: sntp_time
    timezone: UTC

sensor:
  - platform: debug
    free:
      id: sys_heap_free
      state_topic: ${topic_root_stats_system}/heap_free
    loop_time:
      id: sys_loop_time
      state_topic: ${topic_root_stats_system}/loop_time

  - platform: uptime
    id: sys_uptime
    state_topic: ${topic_root_stats_system}/uptime
    update_interval: 5s
 
