substitutions:
  device_name: "worm-gw-test-jig"
  friendly_name: "Worm Control Test Jig"
  mqtt_broker: "mqtt.lan"

packages:
  gw: !include common/gw.yaml

mqtt:
  broker: "$mqtt_broker"

time:
  - platform: sntp
    id: sntp_time
    timezone: "Etc/UTC"

# Switches for relay modules
switch:
  - { platform: gpio, id: M00_R01, name: M00_R01, pin: { worm_relay: wrl, addr: "0000", number: 1 } }
  - { platform: gpio, id: M00_R02, name: M00_R02, pin: { worm_relay: wrl, addr: "0000", number: 2 } }
  - { platform: gpio, id: M00_R03, name: M00_R03, pin: { worm_relay: wrl, addr: "0000", number: 3 } }
  - { platform: gpio, id: M00_R04, name: M00_R04, pin: { worm_relay: wrl, addr: "0000", number: 4 } }
  - { platform: gpio, id: M00_R05, name: M00_R05, pin: { worm_relay: wrl, addr: "0000", number: 5 } }
  - { platform: gpio, id: M00_R06, name: M00_R06, pin: { worm_relay: wrl, addr: "0000", number: 6 } }
  - { platform: gpio, id: M00_R07, name: M00_R07, pin: { worm_relay: wrl, addr: "0000", number: 7 } }
  - { platform: gpio, id: M00_R08, name: M00_R08, pin: { worm_relay: wrl, addr: "0000", number: 8 } }
  - { platform: gpio, id: M00_R09, name: M00_R09, pin: { worm_relay: wrl, addr: "0000", number: 9 } }
  - { platform: gpio, id: M00_R10, name: M00_R10, pin: { worm_relay: wrl, addr: "0000", number: 10 } }
  - { platform: gpio, id: M00_R11, name: M00_R11, pin: { worm_relay: wrl, addr: "0000", number: 11 } }
  - { platform: gpio, id: M00_R12, name: M00_R12, pin: { worm_relay: wrl, addr: "0000", number: 12 } }
  - { platform: gpio, id: M00_R13, name: M00_R13, pin: { worm_relay: wrl, addr: "0000", number: 13 } }
  - { platform: gpio, id: M00_R14, name: M00_R14, pin: { worm_relay: wrl, addr: "0000", number: 14 } }
  - { platform: gpio, id: M00_R15, name: M00_R15, pin: { worm_relay: wrl, addr: "0000", number: 15 } }

  - { platform: gpio, id: M01_R01, name: M01_R01, pin: { worm_relay: wrl, addr: "0001", number: 1 } }
  - { platform: gpio, id: M01_R02, name: M01_R02, pin: { worm_relay: wrl, addr: "0001", number: 2 } }
  - { platform: gpio, id: M01_R03, name: M01_R03, pin: { worm_relay: wrl, addr: "0001", number: 3 } }
  - { platform: gpio, id: M01_R04, name: M01_R04, pin: { worm_relay: wrl, addr: "0001", number: 4 } }
  - { platform: gpio, id: M01_R05, name: M01_R05, pin: { worm_relay: wrl, addr: "0001", number: 5 } }
  - { platform: gpio, id: M01_R06, name: M01_R06, pin: { worm_relay: wrl, addr: "0001", number: 6 } }
  - { platform: gpio, id: M01_R07, name: M01_R07, pin: { worm_relay: wrl, addr: "0001", number: 7 } }
  - { platform: gpio, id: M01_R08, name: M01_R08, pin: { worm_relay: wrl, addr: "0001", number: 8 } }
  - { platform: gpio, id: M01_R09, name: M01_R09, pin: { worm_relay: wrl, addr: "0001", number: 9 } }
  - { platform: gpio, id: M01_R10, name: M01_R10, pin: { worm_relay: wrl, addr: "0001", number: 10 } }
  - { platform: gpio, id: M01_R11, name: M01_R11, pin: { worm_relay: wrl, addr: "0001", number: 11 } }
  - { platform: gpio, id: M01_R12, name: M01_R12, pin: { worm_relay: wrl, addr: "0001", number: 12 } }
  - { platform: gpio, id: M01_R13, name: M01_R13, pin: { worm_relay: wrl, addr: "0001", number: 13 } }
  - { platform: gpio, id: M01_R14, name: M01_R14, pin: { worm_relay: wrl, addr: "0001", number: 14 } }
  - { platform: gpio, id: M01_R15, name: M01_R15, pin: { worm_relay: wrl, addr: "0001", number: 15 } }

# Binary sensors for input modules
binary_sensor:
  - { platform: gpio, id: M00_IN01, name: M00_IN01, pin: { worm_input: win, addr: "0000", number: 1 } }
  - { platform: gpio, id: M00_IN02, name: M00_IN02, pin: { worm_input: win, addr: "0000", number: 2 } }
  - { platform: gpio, id: M00_IN03, name: M00_IN03, pin: { worm_input: win, addr: "0000", number: 3 } }
  - { platform: gpio, id: M00_IN04, name: M00_IN04, pin: { worm_input: win, addr: "0000", number: 4 } }
  - { platform: gpio, id: M00_IN05, name: M00_IN05, pin: { worm_input: win, addr: "0000", number: 5 } }
  - { platform: gpio, id: M00_IN06, name: M00_IN06, pin: { worm_input: win, addr: "0000", number: 6 } }
  - { platform: gpio, id: M00_IN07, name: M00_IN07, pin: { worm_input: win, addr: "0000", number: 7 } }
  - { platform: gpio, id: M00_IN08, name: M00_IN08, pin: { worm_input: win, addr: "0000", number: 8 } }
  - { platform: gpio, id: M00_IN09, name: M00_IN09, pin: { worm_input: win, addr: "0000", number: 9 } }
  - { platform: gpio, id: M00_IN10, name: M00_IN10, pin: { worm_input: win, addr: "0000", number: 10 } }
  - { platform: gpio, id: M00_IN11, name: M00_IN11, pin: { worm_input: win, addr: "0000", number: 11 } }
  - { platform: gpio, id: M00_IN12, name: M00_IN12, pin: { worm_input: win, addr: "0000", number: 12 } }
  - { platform: gpio, id: M00_IN13, name: M00_IN13, pin: { worm_input: win, addr: "0000", number: 13 } }
  - { platform: gpio, id: M00_IN14, name: M00_IN14, pin: { worm_input: win, addr: "0000", number: 14 } }
  - { platform: gpio, id: M00_IN15, name: M00_IN15, pin: { worm_input: win, addr: "0000", number: 15 } }
  - { platform: gpio, id: M00_IN16, name: M00_IN16, pin: { worm_input: win, addr: "0000", number: 16 } }
  - { platform: gpio, id: M00_IN17, name: M00_IN17, pin: { worm_input: win, addr: "0000", number: 17 } }
  - { platform: gpio, id: M00_IN18, name: M00_IN18, pin: { worm_input: win, addr: "0000", number: 18 } }
  - { platform: gpio, id: M00_IN19, name: M00_IN19, pin: { worm_input: win, addr: "0000", number: 19 } }
  - { platform: gpio, id: M00_IN20, name: M00_IN20, pin: { worm_input: win, addr: "0000", number: 20 } }
  - { platform: gpio, id: M00_IN21, name: M00_IN21, pin: { worm_input: win, addr: "0000", number: 21 } }
  - { platform: gpio, id: M00_IN22, name: M00_IN22, pin: { worm_input: win, addr: "0000", number: 22 } }
  - { platform: gpio, id: M00_IN23, name: M00_IN23, pin: { worm_input: win, addr: "0000", number: 23 } }
  - { platform: gpio, id: M00_IN24, name: M00_IN24, pin: { worm_input: win, addr: "0000", number: 24 } }
  - { platform: gpio, id: M00_IN25, name: M00_IN25, pin: { worm_input: win, addr: "0000", number: 25 } }
  - { platform: gpio, id: M00_IN26, name: M00_IN26, pin: { worm_input: win, addr: "0000", number: 26 } }
  - { platform: gpio, id: M00_IN27, name: M00_IN27, pin: { worm_input: win, addr: "0000", number: 27 } }
  - { platform: gpio, id: M00_IN28, name: M00_IN28, pin: { worm_input: win, addr: "0000", number: 28 } }
  - { platform: gpio, id: M00_IN29, name: M00_IN29, pin: { worm_input: win, addr: "0000", number: 29 } }
  - { platform: gpio, id: M00_IN30, name: M00_IN30, pin: { worm_input: win, addr: "0000", number: 30 } }
  - { platform: gpio, id: M00_IN31, name: M00_IN31, pin: { worm_input: win, addr: "0000", number: 31 } }
  - { platform: gpio, id: M00_IN32, name: M00_IN32, pin: { worm_input: win, addr: "0000", number: 32 } }
