substitutions:
  device_name: wormcontrol-gw
  CAN_ID: "0"
  CAN_TX_PIN: "GPIO1"
  CAN_RX_PIN: "GPIO3" 
  root_topic: tmp/device/${device_name}
  update_interval_debug: 5s

packages:
  debug:   !include common/pkg-debug.yaml
  base:    !include gw/pkg-base.yaml 
  time:    !include common/pkg-time.yaml

  relay01: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "0000"}}
  relay02: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "0001"}}
  relay03: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "0010"}}
  relay04: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "0011"}}
  relay05: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "0100"}}
  relay06: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "0101"}}
  relay07: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "0110"}}
  relay08: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "0111"}}
  relay09: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "1000"}}
  relay10: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "1001"}}
  relay11: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "1010"}}
  relay12: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "1011"}}
  relay13: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "1100"}}
  relay14: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "1101"}}
  relay15: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "1110"}}
  relay16: !include {file: gw/pkg-relay-module.yaml, vars: {rl_address: "1111"}}

  input01: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "0000"}}
  input02: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "0001"}}
  input03: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "0010"}}
  input04: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "0011"}}
  input05: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "0100"}}
  input06: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "0101"}}
  input07: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "0110"}}
  input08: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "0111"}}
  input09: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "1000"}}
  input10: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "1001"}}
  input11: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "1010"}}
  input12: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "1011"}}
  input13: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "1100"}}
  input14: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "1101"}}
  input15: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "1110"}}
  input16: !include {file: gw/pkg-input-module.yaml, vars: {inp_address: "1111"}} 

preferences:
  flash_write_interval: 1min

ethernet:
  type: W5500
  # clock_speed: 20Mhz # default is 80/3=26.6
  clk_pin: GPIO12
  mosi_pin: GPIO13
  miso_pin: GPIO9
  cs_pin: GPIO11
  interrupt_pin: GPIO10

canbus:
  - platform: esp32_can
    id: espcan
    tx_pin: ${CAN_TX_PIN}
    rx_pin: ${CAN_RX_PIN}
    can_id: 0
    bit_rate: 125kbps
    on_frame:
      # hello this is my address from relay
      - can_id:      0b00010010000
        can_id_mask: 0b01111110000
        then:
        - lambda: |-
            auto now = id(sntp_time).utcnow().strftime("%Y-%m-%d %H:%M:%SZ");
            std::string b(x.begin(), x.end());
            switch (can_id & 0b00000001111) {
              // case 0b0000: id(RL0000_relay_states).publish_state(b); id(RL0000_lastseen).publish_state(now); break;
              // case 0b0001: id(RL0001_relay_states).publish_state(b); id(RL0001_lastseen).publish_state(now); break;
              // case 0b0010: id(RL0010_relay_states).publish_state(b); id(RL0010_lastseen).publish_state(now); break;
              // case 0b0011: id(RL0011_relay_states).publish_state(b); id(RL0011_lastseen).publish_state(now); break;
              // case 0b0100: id(RL0100_relay_states).publish_state(b); id(RL0100_lastseen).publish_state(now); break;
              // case 0b0101: id(RL0101_relay_states).publish_state(b); id(RL0101_lastseen).publish_state(now); break;
              // case 0b0110: id(RL0110_relay_states).publish_state(b); id(RL0110_lastseen).publish_state(now); break;
              // case 0b0111: id(RL0111_relay_states).publish_state(b); id(RL0111_lastseen).publish_state(now); break;
              // case 0b1000: id(RL1000_relay_states).publish_state(b); id(RL1000_lastseen).publish_state(now); break;
              // case 0b1001: id(RL1001_relay_states).publish_state(b); id(RL1001_lastseen).publish_state(now); break;
              // case 0b1010: id(RL1010_relay_states).publish_state(b); id(RL1010_lastseen).publish_state(now); break;
              // case 0b1011: id(RL1011_relay_states).publish_state(b); id(RL1011_lastseen).publish_state(now); break;
              // case 0b1100: id(RL1100_relay_states).publish_state(b); id(RL1100_lastseen).publish_state(now); break;
              // case 0b1101: id(RL1101_relay_states).publish_state(b); id(RL1101_lastseen).publish_state(now); break;
              // case 0b1110: id(RL1110_relay_states).publish_state(b); id(RL1110_lastseen).publish_state(now); break;
              // case 0b1111: id(RL1111_relay_states).publish_state(b); id(RL1111_lastseen).publish_state(now); break;
            }

mqtt:
  id: mq
  broker: mqtt.lan
  topic_prefix: ${root_topic}/system
