esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

esphome:
  name: wormcontrol-relay
  includes:
    - <bitset>

logger:
  level: INFO
  baud_rate: 921600 

i2c:
  sda: GPIO2
  scl: GPIO8
  frequency: 100kHz
  scan: true

sn74hc595:
  - id: "rl_hub"
    data_pin: GPIO6
    clock_pin: GPIO7
    latch_pin: GPIO10
    sr_count: 2

globals:
  - id: g_can_addr
    type: int
    initial_value: "-1"

  - id: g_relay_states
    type: int[2]

script:
  - id: s_read_my_addr
    then:
      - lambda: |-
          int dip1 = id(can_dip1).state;
          int dip2 = id(can_dip2).state;
          int dip3 = id(can_dip3).state;
          int dip4 = id(can_dip4).state;
          int old_can_addr = id(g_can_addr);
          int new_can_addr = (dip1 << 3) | (dip2 << 2) | (dip3 << 1) | dip4;
          if (old_can_addr != new_can_addr) {
            id(g_can_addr) = new_can_addr;
            
            ESP_LOGI("s_read_my_addr", "relay address change: %s -> %s",
              old_can_addr < 0 ? "n/a" : std::bitset<4>(old_can_addr).to_string().c_str(),
              std::bitset<4>(new_can_addr).to_string().c_str()
            );
            id(s_send_relay_states).execute(); // force publish of new address on change
          }

  - id: s_send_relay_states
    then:
      - lambda: |-
          if (id(g_can_addr) < 0) {
            ESP_LOGI("s_send_relay_states", "g_can_addr not ready yet");
            return;
          }
          std::vector<uint8_t> data(2);
          data[0] = id(g_relay_states)[0];
          data[1] = id(g_relay_states)[1];
          // dev type is 001 for relay module
          uint32_t addr = 0b00010010000 | id(g_can_addr);
          id(espcan).send_data(addr, false, data);

  - id: s_send_sensor_state
    parameters:
      type: int
      index: int
      value: float
    then:
      - lambda: |-
          if (id(g_can_addr) < 0) {
            ESP_LOGI("s_send_sensor_state", "g_can_addr not ready yet");
            return;
          }
          uint32_t raw = *reinterpret_cast<uint32_t*>(&value);                  
          uint32_t header = ((type & 0x0F) << 4) | (index & 0x0F);
          //ESP_LOGI("s_states", "header bits = %s", std::bitset<12>(header).to_string().c_str());
          uint64_t payload = (static_cast<uint64_t>(header & 0xFFF) << 32) | raw;      
          std::vector<unsigned char> data(6);
          for (int i = 0; i < 6; i++) {
            data[i] = (payload >> (i * 8)) & 0xFF;
          }
          uint32_t addr = 0b10010100000 | id(g_can_addr);  // 0b1 - lower priority ; 001 - dev type; 010 - monitoring
          id(espcan).send_data(addr, false, data);        

switch:
  # relays through expander
  - { platform: gpio, id: "RL00", pin: { sn74hc595: rl_hub, number: 0 } }
  - { platform: gpio, id: "RL01", pin: { sn74hc595: rl_hub, number: 1 } }
  - { platform: gpio, id: "RL02", pin: { sn74hc595: rl_hub, number: 2 } }
  - { platform: gpio, id: "RL03", pin: { sn74hc595: rl_hub, number: 3 } }
  - { platform: gpio, id: "RL04", pin: { sn74hc595: rl_hub, number: 4 } }
  - { platform: gpio, id: "RL05", pin: { sn74hc595: rl_hub, number: 5 } }
  - { platform: gpio, id: "RL06", pin: { sn74hc595: rl_hub, number: 6 } }
  - { platform: gpio, id: "RL07", pin: { sn74hc595: rl_hub, number: 7 } }
  - { platform: gpio, id: "RL08", pin: { sn74hc595: rl_hub, number: 8 } }
  - { platform: gpio, id: "RL09", pin: { sn74hc595: rl_hub, number: 9 } }
  - { platform: gpio, id: "RL10", pin: { sn74hc595: rl_hub, number: 10 } }
  - { platform: gpio, id: "RL11", pin: { sn74hc595: rl_hub, number: 11 } }
  - { platform: gpio, id: "RL12", pin: { sn74hc595: rl_hub, number: 12 } }
  - { platform: gpio, id: "RL13", pin: { sn74hc595: rl_hub, number: 13 } }
  - { platform: gpio, id: "RL14", pin: { sn74hc595: rl_hub, number: 14 } }
  - { platform: gpio, id: "RL15", pin: { sn74hc595: rl_hub, number: 15 } }

binary_sensor:
  # canbus address dip switches
  - platform: gpio
    id: can_dip1
    pin: { number: GPIO5, inverted: true, mode: { input: true, pullup: true } }
    filters: { delayed_on_off: 1s }
  - platform: gpio
    id: can_dip2
    pin: { number: GPIO4, inverted: true, mode: { input: true, pullup: true } }
    filters: { delayed_on_off: 1s }
  - platform: gpio
    id: can_dip3
    pin: { number: GPIO3, inverted: true, mode: { input: true, pullup: true } }
    filters: { delayed_on_off: 1s }
  - platform: gpio
    id: can_dip4
    pin: { number: GPIO1, inverted: true, mode: { input: true, pullup: true } }
    filters: { delayed_on_off: 1s }

canbus:
  - platform: esp32_can
    id: espcan
    tx_pin: GPIO21
    rx_pin: GPIO20
    can_id: 0
    bit_rate: 125kbps
    on_frame:
      # relay control message from gw
      - can_id: 0b10000000000
        can_id_mask: 0b11111110000
        then:
          - lambda: |-
              if ((can_id & 0b00000001111) == id(g_can_addr)) {
                if (x.size() != 2) {
                  ESP_LOGD("lambda", "Received an invalid control message from gateway (size %d)", x.size());
                  return;
                }
                id(g_relay_states)[0] = x[0];
                id(g_relay_states)[1] = x[1];
                ESP_LOGD("lambda", "Got control msg from gw: %s %s", std::bitset<8>(x[0]).to_string().c_str(), std::bitset<8>(x[1]).to_string().c_str());
                // At this point x is a vector of two uint8 items. Need to turn on relays the bit is high and turn off when it is low.
                (x[0] >> 0 & 1) ? id(RL00).turn_on() : id(RL00).turn_off();
                (x[0] >> 1 & 1) ? id(RL01).turn_on() : id(RL01).turn_off();
                (x[0] >> 2 & 1) ? id(RL02).turn_on() : id(RL02).turn_off();
                (x[0] >> 3 & 1) ? id(RL03).turn_on() : id(RL03).turn_off();
                (x[0] >> 4 & 1) ? id(RL04).turn_on() : id(RL04).turn_off();
                (x[0] >> 5 & 1) ? id(RL05).turn_on() : id(RL05).turn_off();
                (x[0] >> 6 & 1) ? id(RL06).turn_on() : id(RL06).turn_off();
                (x[0] >> 7 & 1) ? id(RL07).turn_on() : id(RL07).turn_off();

                (x[1] >> 0 & 1) ? id(RL08).turn_on() : id(RL08).turn_off();
                (x[1] >> 1 & 1) ? id(RL09).turn_on() : id(RL09).turn_off();
                (x[1] >> 2 & 1) ? id(RL10).turn_on() : id(RL10).turn_off();
                (x[1] >> 3 & 1) ? id(RL11).turn_on() : id(RL11).turn_off();
                (x[1] >> 4 & 1) ? id(RL12).turn_on() : id(RL12).turn_off();
                (x[1] >> 5 & 1) ? id(RL13).turn_on() : id(RL13).turn_off();
                (x[1] >> 6 & 1) ? id(RL14).turn_on() : id(RL14).turn_off();
                (x[1] >> 7 & 1) ? id(RL15).turn_on() : id(RL15).turn_off();
              }

interval:
  - interval: 10s
    startup_delay: 1s
    then:
      - lambda: |-
          id(s_send_relay_states).execute();

  - interval: 1s
    # NOTE the first run of this interval must be synced with dip switch gpio debounce
    startup_delay: 1s
    then:
      - lambda: |-
          id(s_read_my_addr).execute();

sensor:
  - platform: tmp102 # UI panel temp. sensor
    id: temp_1
    address: 0x48
    update_interval: 4000ms
    force_update: True
    on_value:
      then:
        - script.execute:
            id: s_send_sensor_state
            type: 1 # 0b001 Temperature
            index: 1
            value: !lambda "return id(temp_1).state;"  
  - platform: tmp102 # Relay PCB temp. sensor
    id: temp_2
    address: 0x49
    update_interval: 4100ms
    force_update: True
    on_value:
      then:
        - script.execute:
            id: s_send_sensor_state
            type: 1 # 0b001 Temperature
            index: 2
            value: !lambda "return id(temp_2).state;"  
  - platform: tmp102 # Middle PCB temp. sensor
    id: temp_3
    address: 0x4A
    update_interval: 4200ms
    force_update: True
    on_value:
      then:
        - script.execute:
            id: s_send_sensor_state
            type: 1 # 0b001 Temperature
            index: 3
            value: !lambda "return id(temp_3).state;"  
  - platform: adc
    pin: GPIO00
    id: adc_voltage
    update_interval: 4300ms
    force_update: True
    filters:
      - calibrate_linear:
        - 0.750 -> 24.686
        - 0.000 -> 0
    on_value:
      then:
        - script.execute:
            id: s_send_sensor_state
            type: 3 # 0b011 Voltage
            index: 0
            value: !lambda "return id(adc_voltage).state;"  
