debug:
  update_interval: ${update_interval_debug}

sensor:
  - platform: debug
    free:
      id: sys_heap_free
      state_topic: ${root_topic}/system/heap_free
    loop_time:
      id: sys_loop_time
      state_topic: ${root_topic}/system/loop_time
    psram:
      id: sys_psram_free
      state_topic: ${root_topic}/system/psram_free

  - platform: uptime
    id: sys_uptime
    state_topic: ${root_topic}/system/uptime
    update_interval: ${update_interval_debug}

